/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.achaeu;

import autenticacao.UsuarioManager;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import view.FrmLogon;
import view.FrmNovoLocal;

/**
 *
 * @author jonathan
 */
public class BrComAchaeu extends javax.swing.JFrame {

    /**
     * Creates new form BrComAchaeu
     */
    public BrComAchaeu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mnuMain = new javax.swing.JMenuBar();
        mnuUsuario = new javax.swing.JMenu();
        mnuLogon = new javax.swing.JMenuItem();
        mnuLogoff = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mnuUsuario.setText("Usuário");

        mnuLogon.setText("Logon");
        mnuLogon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuLogonActionPerformed(evt);
            }
        });
        mnuUsuario.add(mnuLogon);

        mnuLogoff.setText("Logoff");
        mnuLogoff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuLogoffActionPerformed(evt);
            }
        });
        mnuUsuario.add(mnuLogoff);

        mnuMain.add(mnuUsuario);

        setJMenuBar(mnuMain);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 620, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 389, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void definirVisibilidadeDosItensDeMenu() {
        boolean visivel = UsuarioManager.isUserLogged();
        mnuLogon.setVisible(!visivel);
        mnuLogoff.setVisible(visivel);
    }
    
    private void mnuLogonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuLogonActionPerformed
        UsuarioManager.logOff();
        FrmLogon frmLogon = new FrmLogon(this, true);
        frmLogon.setLocationRelativeTo(this);
        frmLogon.setVisible(true);

        if (frmLogon.loginComSucesso()) {
            this.definirVisibilidadeDosItensDeMenu();
        }
    }//GEN-LAST:event_mnuLogonActionPerformed

    private void mnuLogoffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuLogoffActionPerformed
        if (JOptionPane.showConfirmDialog(this, "Deseja mesmo fazer logoff?", "Logoff", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
            UsuarioManager.logOff();
            this.definirVisibilidadeDosItensDeMenu();
        }

    }//GEN-LAST:event_mnuLogoffActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BrComAchaeu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BrComAchaeu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BrComAchaeu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BrComAchaeu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                BrComAchaeu main = new BrComAchaeu();
                main.setExtendedState(JFrame.MAXIMIZED_BOTH);
                main.definirVisibilidadeDosItensDeMenu();
                main.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem mnuLogoff;
    private javax.swing.JMenuItem mnuLogon;
    private javax.swing.JMenuBar mnuMain;
    private javax.swing.JMenu mnuUsuario;
    // End of variables declaration//GEN-END:variables
}
