-- MySQL Script generated by MySQL Workbench
-- Tue 05 Jun 2018 09:08:52 PM -04
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema ACHA_EU
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ACHA_EU
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ACHA_EU` DEFAULT CHARACTER SET utf8 ;
USE `ACHA_EU` ;

-- -----------------------------------------------------
-- Table `ACHA_EU`.`CATEGORIA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ACHA_EU`.`CATEGORIA` (
  `ID` INT(11) NOT NULL,
  `NOME` VARCHAR(45) NULL DEFAULT NULL,
  `TAGS` VARCHAR(300) NULL DEFAULT NULL,
  `ID_CAT_PAI` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `ACHA_EU`.`LOCALIZACAO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ACHA_EU`.`LOCALIZACAO` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT COMMENT 'Identificador da tabela de localizações.',
  `LATITUDE` DOUBLE NULL DEFAULT NULL COMMENT 'Define a latitude da localização.',
  `LONGITUDE` DOUBLE NULL DEFAULT NULL COMMENT 'Define a longitude da localização.',
  PRIMARY KEY (`ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `ACHA_EU`.`ENDERECO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ACHA_EU`.`ENDERECO` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT COMMENT 'Identificador da tabela de endereços.',
  `LOGRADOURO` VARCHAR(50) NULL DEFAULT NULL COMMENT 'Define o logradouro do endereço.',
  `NUMERO` INT(11) NULL DEFAULT NULL COMMENT 'Define o número do endereço.',
  `BAIRRO` VARCHAR(45) NULL DEFAULT NULL COMMENT 'Define o bairro do endereço.',
  `CEP` VARCHAR(8) NULL DEFAULT NULL COMMENT 'Define o CEP do endereço.',
  `CIDADE` VARCHAR(50) NULL DEFAULT NULL COMMENT 'Define a cidade do endereço.',
  `UF` VARCHAR(2) NULL DEFAULT NULL COMMENT 'Define a UF do endereço.',
  `ID_LOCALIZACAO` INT(11) NULL DEFAULT NULL COMMENT 'Pega uma localização cadastrada e vincula ela ao endereço.',
  PRIMARY KEY (`ID`),
  INDEX `ID_LOCALIZACAO_FK_idx` (`ID_LOCALIZACAO` ASC),
  CONSTRAINT `ID_LOCALIZACAO_FK`
    FOREIGN KEY (`ID_LOCALIZACAO`)
    REFERENCES `ACHA_EU`.`LOCALIZACAO` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `ACHA_EU`.`USUARIO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ACHA_EU`.`USUARIO` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT COMMENT 'Identificador da tabela de usuários.',
  `NOME` VARCHAR(45) NULL DEFAULT NULL COMMENT 'Define o nome do usuário.',
  `EMAIL` VARCHAR(45) NULL DEFAULT NULL COMMENT 'Define o e-mail do usuário.',
  `SENHA` VARCHAR(45) NULL DEFAULT NULL COMMENT 'Define a senha do usuário.',
  `NIVEL` INT(11) NULL DEFAULT NULL COMMENT 'Define o nível de acesso do usuário.',
  `DATA_CRIACAO` TIMESTAMP NULL DEFAULT NULL,
  `DATA_ALTERACAO` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `ACHA_EU`.`LOCAL`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ACHA_EU`.`LOCAL` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT COMMENT 'Identificador da tabela de locais.',
  `NOME` VARCHAR(45) NULL DEFAULT NULL COMMENT 'Define o nome do local.',
  `DESCRICAO` VARCHAR(150) NULL DEFAULT NULL COMMENT 'Permite inserir uma descrição do local.',
  `DATA_CRIACAO` TIMESTAMP NULL DEFAULT NULL COMMENT 'Define a data de criação do registro.',
  `DATA_ALTERACAO` TIMESTAMP NULL DEFAULT NULL COMMENT 'Define a data de alteração do registro.',
  `ID_USUARIO` INT(11) NULL DEFAULT NULL COMMENT 'Define qual usuário criou o local.',
  `ID_ENDERECO` INT(11) NULL DEFAULT NULL COMMENT 'Define qual é o endereço do local.',
  `TELEFONE_1` VARCHAR(20) NULL DEFAULT NULL COMMENT 'Define o primeiro telefone do registro.',
  `TELEFONE_2` VARCHAR(20) NULL DEFAULT NULL COMMENT 'Define o segundo telefone do registro.',
  `ID_CATEGORIA` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`ID`),
  INDEX `CRIADO_POR_FK_idx` (`ID_USUARIO` ASC),
  INDEX `ID_ENDERECO_idx` (`ID_ENDERECO` ASC),
  INDEX `ID_CATEGORIA_idx` (`ID_CATEGORIA` ASC),
  CONSTRAINT `ID_CATEGORIA_FK`
    FOREIGN KEY (`ID_CATEGORIA`)
    REFERENCES `ACHA_EU`.`CATEGORIA` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `ID_ENDERECO`
    FOREIGN KEY (`ID_ENDERECO`)
    REFERENCES `ACHA_EU`.`ENDERECO` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `ID_USUARIO_FK`
    FOREIGN KEY (`ID_USUARIO`)
    REFERENCES `ACHA_EU`.`USUARIO` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `ACHA_EU`.`AVALIACAO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ACHA_EU`.`AVALIACAO` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT COMMENT 'Identificador da tabela de avaliações.',
  `CONTEUDO` VARCHAR(150) NULL DEFAULT NULL COMMENT 'Define o corpo da avaliação.',
  `ID_USUARIO` INT(11) NULL DEFAULT NULL COMMENT 'Vincula esta avaliação a um usuário.',
  `NOTA` DECIMAL(10,0) NULL DEFAULT NULL COMMENT 'Define, de 0 a 5, a nota do local.',
  `ID_LOCAL` INT(11) NULL DEFAULT NULL COMMENT 'Vincula esta avaliação a um local.',
  `DATA_CRIACAO` TIMESTAMP NULL DEFAULT NULL COMMENT 'Data em que o registro foi criado.',
  `DATA_ALTERACAO` TIMESTAMP NULL DEFAULT NULL COMMENT 'Data em que o registro foi alterado.',
  PRIMARY KEY (`ID`),
  INDEX `ID_USUARIO_FK_idx` (`ID_USUARIO` ASC),
  INDEX `ID_LOCAL_idx` (`ID_LOCAL` ASC),
  CONSTRAINT `ID_LOCAL`
    FOREIGN KEY (`ID_LOCAL`)
    REFERENCES `ACHA_EU`.`LOCAL` (`ID`),
  CONSTRAINT `ID_USUARIO_AVALIACAO_FK`
    FOREIGN KEY (`ID_USUARIO`)
    REFERENCES `ACHA_EU`.`USUARIO` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `ACHA_EU`.`FOTO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ACHA_EU`.`FOTO` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT COMMENT 'Identificador da tabela de fotos.',
  `DIRETORIO_ABSOLUTO` VARCHAR(150) NULL DEFAULT NULL COMMENT 'Define o diretório absoluto (Caminho + arquivo) da foto a salvar.',
  `ID_LOCAL` INT(11) NULL DEFAULT NULL COMMENT 'Vincula esta foto a um local.',
  PRIMARY KEY (`ID`),
  INDEX `ID_LOCAL_FK_idx` (`ID_LOCAL` ASC),
  CONSTRAINT `ID_LOCAL_FOTO_FK`
    FOREIGN KEY (`ID_LOCAL`)
    REFERENCES `ACHA_EU`.`LOCAL` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `ACHA_EU`.`HORARIO_LOCAL`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ACHA_EU`.`HORARIO_LOCAL` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT COMMENT 'Identificador da tabela de horários e locais. Esta tabela vinculará muitos horários a muitos locais.',
  `ENTRADA_1` TIME NULL DEFAULT NULL,
  `SAIDA_1` TIME NULL DEFAULT NULL,
  `ENTRADA_2` TIME NULL DEFAULT NULL,
  `SAIDA_2` TIME NULL DEFAULT NULL,
  `FUNCIONAMENTO` INT(11) NULL DEFAULT NULL,
  `DIA_SEMANA` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
